'use client';

import React from 'react';
import { MdPrint } from 'react-icons/md';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

const PrintExpenseReport = ({
    data = [],
    reportTitle = 'Expense Report',
}) => {

    const handlePrint = () => {

        if (!data.length) {
            alert('No expense data found!');
            return;
        }

        const doc = new jsPDF({
            orientation: 'portrait',
            unit: 'mm',
            format: 'a4'
        });

        // ================= HEADER =================

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(20);
        doc.setTextColor(30, 41, 59);
        doc.text('ICC Communication', 14, 18);

        doc.setFontSize(14);
        doc.setTextColor(37, 99, 235);
        doc.text(reportTitle, 14, 27);

        doc.setDrawColor(37, 99, 235);
        doc.line(14, 31, 196, 31);

        // ================= INFO =================

        const totalAmount = data.reduce(
            (sum, item) => sum + Number(item.amount || 0),
            0
        );

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        doc.setTextColor(100, 116, 139);

        doc.text(
            `Generated : ${new Date().toLocaleString()}`,
            14,
            38
        );

        doc.text(
            `Total Records : ${data.length}`,
            14,
            44
        );

        doc.setFont('helvetica', 'bold');
        doc.setTextColor(220, 38, 38);

        doc.text(
            `Total Expense : BDT ${totalAmount.toFixed(2)}`,
            14,
            50
        );

        // ================= TABLE =================

        const rows = data.map((item, index) => [
            index + 1,
            item.title || '-',
            item.category || 'General',
            `${Number(item.amount).toFixed(2)}`,
            item.note || '-',
            item.expenseDate
                ? new Date(item.expenseDate).toLocaleDateString()
                : '-',
        ]);

        autoTable(doc, {
            startY: 58,

            head: [[
                '#',
                'Title',
                'Category',
                'Amount',
                'Note',
                'Date'
            ]],

            body: rows,

            theme: 'striped',

            headStyles: {
                fillColor: [37, 99, 235],
                textColor: 255,
                fontStyle: 'bold',
                fontSize: 10,
                halign: 'center'
            },

            alternateRowStyles: {
                fillColor: [248, 250, 252]
            },

            styles: {
                font: 'helvetica',
                fontSize: 9,
                cellPadding: 3,
                overflow: 'linebreak'
            },

            columnStyles: {
                0: {
                    cellWidth: 12,
                    halign: 'center'
                },
                1: {
                    cellWidth: 42
                },
                2: {
                    cellWidth: 35
                },
                3: {
                    cellWidth: 28,
                    halign: 'right'
                },
                4: {
                    cellWidth: 48
                },
                5: {
                    cellWidth: 28,
                    halign: 'center'
                }
            },

            didDrawPage: () => {

                const pageCount = doc.getNumberOfPages();

                doc.setFontSize(9);
                doc.setTextColor(120);

                doc.text(
                    `Page ${pageCount}`,
                    180,
                    290
                );

                doc.text(
                    'Generated By Mahialam Rahat',
                    14,
                    290
                );
            }

        });

        // ================= OPEN PDF =================

        const pdfBlob = doc.output('blob');

        const pdfUrl = URL.createObjectURL(pdfBlob);

        window.open(pdfUrl, '_blank');
    };

    return (
        <button
            onClick={handlePrint}
            className="inline-flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-xl font-semibold text-sm transition cursor-pointer"
        >
            <MdPrint size={18} />
            Print Report
        </button>
    );
};

export default PrintExpenseReport;